// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datamover.proto

package datamover

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AbortJobRequest struct {
	Context              string   `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbortJobRequest) Reset()         { *m = AbortJobRequest{} }
func (m *AbortJobRequest) String() string { return proto.CompactTextString(m) }
func (*AbortJobRequest) ProtoMessage()    {}
func (*AbortJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{0}
}

func (m *AbortJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbortJobRequest.Unmarshal(m, b)
}
func (m *AbortJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbortJobRequest.Marshal(b, m, deterministic)
}
func (m *AbortJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbortJobRequest.Merge(m, src)
}
func (m *AbortJobRequest) XXX_Size() int {
	return xxx_messageInfo_AbortJobRequest.Size(m)
}
func (m *AbortJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AbortJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AbortJobRequest proto.InternalMessageInfo

func (m *AbortJobRequest) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *AbortJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type AbortJobResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AbortJobResponse) Reset()         { *m = AbortJobResponse{} }
func (m *AbortJobResponse) String() string { return proto.CompactTextString(m) }
func (*AbortJobResponse) ProtoMessage()    {}
func (*AbortJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{1}
}

func (m *AbortJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AbortJobResponse.Unmarshal(m, b)
}
func (m *AbortJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AbortJobResponse.Marshal(b, m, deterministic)
}
func (m *AbortJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AbortJobResponse.Merge(m, src)
}
func (m *AbortJobResponse) XXX_Size() int {
	return xxx_messageInfo_AbortJobResponse.Size(m)
}
func (m *AbortJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AbortJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AbortJobResponse proto.InternalMessageInfo

func (m *AbortJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *AbortJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AbortJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type PauseJobRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseJobRequest) Reset()         { *m = PauseJobRequest{} }
func (m *PauseJobRequest) String() string { return proto.CompactTextString(m) }
func (*PauseJobRequest) ProtoMessage()    {}
func (*PauseJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{2}
}

func (m *PauseJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseJobRequest.Unmarshal(m, b)
}
func (m *PauseJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseJobRequest.Marshal(b, m, deterministic)
}
func (m *PauseJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseJobRequest.Merge(m, src)
}
func (m *PauseJobRequest) XXX_Size() int {
	return xxx_messageInfo_PauseJobRequest.Size(m)
}
func (m *PauseJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PauseJobRequest proto.InternalMessageInfo

func (m *PauseJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type PauseJobResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PauseJobResponse) Reset()         { *m = PauseJobResponse{} }
func (m *PauseJobResponse) String() string { return proto.CompactTextString(m) }
func (*PauseJobResponse) ProtoMessage()    {}
func (*PauseJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{3}
}

func (m *PauseJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PauseJobResponse.Unmarshal(m, b)
}
func (m *PauseJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PauseJobResponse.Marshal(b, m, deterministic)
}
func (m *PauseJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PauseJobResponse.Merge(m, src)
}
func (m *PauseJobResponse) XXX_Size() int {
	return xxx_messageInfo_PauseJobResponse.Size(m)
}
func (m *PauseJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PauseJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PauseJobResponse proto.InternalMessageInfo

func (m *PauseJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func (m *PauseJobResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PauseJobResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type KV struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KV) Reset()         { *m = KV{} }
func (m *KV) String() string { return proto.CompactTextString(m) }
func (*KV) ProtoMessage()    {}
func (*KV) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{4}
}

func (m *KV) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KV.Unmarshal(m, b)
}
func (m *KV) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KV.Marshal(b, m, deterministic)
}
func (m *KV) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KV.Merge(m, src)
}
func (m *KV) XXX_Size() int {
	return xxx_messageInfo_KV.Size(m)
}
func (m *KV) XXX_DiscardUnknown() {
	xxx_messageInfo_KV.DiscardUnknown(m)
}

var xxx_messageInfo_KV proto.InternalMessageInfo

func (m *KV) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *KV) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type Filter struct {
	Prefix               string   `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Tag                  []*KV    `protobuf:"bytes,2,rep,name=tag,proto3" json:"tag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Filter) Reset()         { *m = Filter{} }
func (m *Filter) String() string { return proto.CompactTextString(m) }
func (*Filter) ProtoMessage()    {}
func (*Filter) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{5}
}

func (m *Filter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Filter.Unmarshal(m, b)
}
func (m *Filter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Filter.Marshal(b, m, deterministic)
}
func (m *Filter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Filter.Merge(m, src)
}
func (m *Filter) XXX_Size() int {
	return xxx_messageInfo_Filter.Size(m)
}
func (m *Filter) XXX_DiscardUnknown() {
	xxx_messageInfo_Filter.DiscardUnknown(m)
}

var xxx_messageInfo_Filter proto.InternalMessageInfo

func (m *Filter) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Filter) GetTag() []*KV {
	if m != nil {
		return m.Tag
	}
	return nil
}

type Connector struct {
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=BucketName,proto3" json:"BucketName,omitempty"`
	ConnConfig           []*KV    `protobuf:"bytes,3,rep,name=ConnConfig,proto3" json:"ConnConfig,omitempty"`
	BackendName          string   `protobuf:"bytes,4,opt,name=BackendName,proto3" json:"BackendName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Connector) Reset()         { *m = Connector{} }
func (m *Connector) String() string { return proto.CompactTextString(m) }
func (*Connector) ProtoMessage()    {}
func (*Connector) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{6}
}

func (m *Connector) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connector.Unmarshal(m, b)
}
func (m *Connector) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connector.Marshal(b, m, deterministic)
}
func (m *Connector) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connector.Merge(m, src)
}
func (m *Connector) XXX_Size() int {
	return xxx_messageInfo_Connector.Size(m)
}
func (m *Connector) XXX_DiscardUnknown() {
	xxx_messageInfo_Connector.DiscardUnknown(m)
}

var xxx_messageInfo_Connector proto.InternalMessageInfo

func (m *Connector) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Connector) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *Connector) GetConnConfig() []*KV {
	if m != nil {
		return m.ConnConfig
	}
	return nil
}

func (m *Connector) GetBackendName() string {
	if m != nil {
		return m.BackendName
	}
	return ""
}

type RunJobRequest struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenanId              string     `protobuf:"bytes,2,opt,name=tenanId,proto3" json:"tenanId,omitempty"`
	UserId               string     `protobuf:"bytes,3,opt,name=userId,proto3" json:"userId,omitempty"`
	SourceConn           *Connector `protobuf:"bytes,4,opt,name=sourceConn,proto3" json:"sourceConn,omitempty"`
	DestConn             *Connector `protobuf:"bytes,5,opt,name=destConn,proto3" json:"destConn,omitempty"`
	Filt                 *Filter    `protobuf:"bytes,6,opt,name=filt,proto3" json:"filt,omitempty"`
	RemainSource         bool       `protobuf:"varint,7,opt,name=remainSource,proto3" json:"remainSource,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *RunJobRequest) Reset()         { *m = RunJobRequest{} }
func (m *RunJobRequest) String() string { return proto.CompactTextString(m) }
func (*RunJobRequest) ProtoMessage()    {}
func (*RunJobRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{7}
}

func (m *RunJobRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunJobRequest.Unmarshal(m, b)
}
func (m *RunJobRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunJobRequest.Marshal(b, m, deterministic)
}
func (m *RunJobRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunJobRequest.Merge(m, src)
}
func (m *RunJobRequest) XXX_Size() int {
	return xxx_messageInfo_RunJobRequest.Size(m)
}
func (m *RunJobRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RunJobRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RunJobRequest proto.InternalMessageInfo

func (m *RunJobRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RunJobRequest) GetTenanId() string {
	if m != nil {
		return m.TenanId
	}
	return ""
}

func (m *RunJobRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *RunJobRequest) GetSourceConn() *Connector {
	if m != nil {
		return m.SourceConn
	}
	return nil
}

func (m *RunJobRequest) GetDestConn() *Connector {
	if m != nil {
		return m.DestConn
	}
	return nil
}

func (m *RunJobRequest) GetFilt() *Filter {
	if m != nil {
		return m.Filt
	}
	return nil
}

func (m *RunJobRequest) GetRemainSource() bool {
	if m != nil {
		return m.RemainSource
	}
	return false
}

type RunJobResponse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RunJobResponse) Reset()         { *m = RunJobResponse{} }
func (m *RunJobResponse) String() string { return proto.CompactTextString(m) }
func (*RunJobResponse) ProtoMessage()    {}
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{8}
}

func (m *RunJobResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RunJobResponse.Unmarshal(m, b)
}
func (m *RunJobResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RunJobResponse.Marshal(b, m, deterministic)
}
func (m *RunJobResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RunJobResponse.Merge(m, src)
}
func (m *RunJobResponse) XXX_Size() int {
	return xxx_messageInfo_RunJobResponse.Size(m)
}
func (m *RunJobResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RunJobResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RunJobResponse proto.InternalMessageInfo

func (m *RunJobResponse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

type LifecycleActionRequest struct {
	ObjKey               string   `protobuf:"bytes,1,opt,name=objKey,proto3" json:"objKey,omitempty"`
	BucketName           string   `protobuf:"bytes,2,opt,name=bucketName,proto3" json:"bucketName,omitempty"`
	VersionId            string   `protobuf:"bytes,3,opt,name=versionId,proto3" json:"versionId,omitempty"`
	StorageMeta          string   `protobuf:"bytes,4,opt,name=storageMeta,proto3" json:"storageMeta,omitempty"`
	ObjectId             string   `protobuf:"bytes,5,opt,name=objectId,proto3" json:"objectId,omitempty"`
	Action               int32    `protobuf:"varint,6,opt,name=action,proto3" json:"action,omitempty"`
	SourceTier           int32    `protobuf:"varint,7,opt,name=sourceTier,proto3" json:"sourceTier,omitempty"`
	TargetTier           int32    `protobuf:"varint,8,opt,name=targetTier,proto3" json:"targetTier,omitempty"`
	SourceBackend        string   `protobuf:"bytes,9,opt,name=sourceBackend,proto3" json:"sourceBackend,omitempty"`
	TargetBackend        string   `protobuf:"bytes,10,opt,name=targetBackend,proto3" json:"targetBackend,omitempty"`
	ObjSize              int64    `protobuf:"varint,11,opt,name=objSize,proto3" json:"objSize,omitempty"`
	UploadId             string   `protobuf:"bytes,12,opt,name=uploadId,proto3" json:"uploadId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifecycleActionRequest) Reset()         { *m = LifecycleActionRequest{} }
func (m *LifecycleActionRequest) String() string { return proto.CompactTextString(m) }
func (*LifecycleActionRequest) ProtoMessage()    {}
func (*LifecycleActionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{9}
}

func (m *LifecycleActionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleActionRequest.Unmarshal(m, b)
}
func (m *LifecycleActionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleActionRequest.Marshal(b, m, deterministic)
}
func (m *LifecycleActionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleActionRequest.Merge(m, src)
}
func (m *LifecycleActionRequest) XXX_Size() int {
	return xxx_messageInfo_LifecycleActionRequest.Size(m)
}
func (m *LifecycleActionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleActionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleActionRequest proto.InternalMessageInfo

func (m *LifecycleActionRequest) GetObjKey() string {
	if m != nil {
		return m.ObjKey
	}
	return ""
}

func (m *LifecycleActionRequest) GetBucketName() string {
	if m != nil {
		return m.BucketName
	}
	return ""
}

func (m *LifecycleActionRequest) GetVersionId() string {
	if m != nil {
		return m.VersionId
	}
	return ""
}

func (m *LifecycleActionRequest) GetStorageMeta() string {
	if m != nil {
		return m.StorageMeta
	}
	return ""
}

func (m *LifecycleActionRequest) GetObjectId() string {
	if m != nil {
		return m.ObjectId
	}
	return ""
}

func (m *LifecycleActionRequest) GetAction() int32 {
	if m != nil {
		return m.Action
	}
	return 0
}

func (m *LifecycleActionRequest) GetSourceTier() int32 {
	if m != nil {
		return m.SourceTier
	}
	return 0
}

func (m *LifecycleActionRequest) GetTargetTier() int32 {
	if m != nil {
		return m.TargetTier
	}
	return 0
}

func (m *LifecycleActionRequest) GetSourceBackend() string {
	if m != nil {
		return m.SourceBackend
	}
	return ""
}

func (m *LifecycleActionRequest) GetTargetBackend() string {
	if m != nil {
		return m.TargetBackend
	}
	return ""
}

func (m *LifecycleActionRequest) GetObjSize() int64 {
	if m != nil {
		return m.ObjSize
	}
	return 0
}

func (m *LifecycleActionRequest) GetUploadId() string {
	if m != nil {
		return m.UploadId
	}
	return ""
}

type LifecycleActionResonse struct {
	Err                  string   `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LifecycleActionResonse) Reset()         { *m = LifecycleActionResonse{} }
func (m *LifecycleActionResonse) String() string { return proto.CompactTextString(m) }
func (*LifecycleActionResonse) ProtoMessage()    {}
func (*LifecycleActionResonse) Descriptor() ([]byte, []int) {
	return fileDescriptor_302d3374d95ec8eb, []int{10}
}

func (m *LifecycleActionResonse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LifecycleActionResonse.Unmarshal(m, b)
}
func (m *LifecycleActionResonse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LifecycleActionResonse.Marshal(b, m, deterministic)
}
func (m *LifecycleActionResonse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LifecycleActionResonse.Merge(m, src)
}
func (m *LifecycleActionResonse) XXX_Size() int {
	return xxx_messageInfo_LifecycleActionResonse.Size(m)
}
func (m *LifecycleActionResonse) XXX_DiscardUnknown() {
	xxx_messageInfo_LifecycleActionResonse.DiscardUnknown(m)
}

var xxx_messageInfo_LifecycleActionResonse proto.InternalMessageInfo

func (m *LifecycleActionResonse) GetErr() string {
	if m != nil {
		return m.Err
	}
	return ""
}

func init() {
	proto.RegisterType((*AbortJobRequest)(nil), "AbortJobRequest")
	proto.RegisterType((*AbortJobResponse)(nil), "AbortJobResponse")
	proto.RegisterType((*PauseJobRequest)(nil), "PauseJobRequest")
	proto.RegisterType((*PauseJobResponse)(nil), "PauseJobResponse")
	proto.RegisterType((*KV)(nil), "KV")
	proto.RegisterType((*Filter)(nil), "Filter")
	proto.RegisterType((*Connector)(nil), "Connector")
	proto.RegisterType((*RunJobRequest)(nil), "RunJobRequest")
	proto.RegisterType((*RunJobResponse)(nil), "RunJobResponse")
	proto.RegisterType((*LifecycleActionRequest)(nil), "LifecycleActionRequest")
	proto.RegisterType((*LifecycleActionResonse)(nil), "LifecycleActionResonse")
}

func init() { proto.RegisterFile("datamover.proto", fileDescriptor_302d3374d95ec8eb) }

var fileDescriptor_302d3374d95ec8eb = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x54, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0xae, 0xe3, 0x26, 0x4d, 0x26, 0x6d, 0x93, 0xae, 0x7e, 0xbf, 0x62, 0x05, 0x84, 0x82, 0x41,
	0x28, 0x2a, 0xc8, 0x12, 0xe5, 0xc0, 0x81, 0x53, 0x5b, 0x04, 0x0a, 0x2d, 0x08, 0xb9, 0x55, 0xef,
	0x6b, 0x7b, 0x12, 0x39, 0x49, 0x77, 0xc3, 0xee, 0xba, 0x6a, 0x78, 0x80, 0x3e, 0x2a, 0xbc, 0x06,
	0xda, 0xb5, 0x37, 0x71, 0xdc, 0xf4, 0xc4, 0x6d, 0xbf, 0x6f, 0xfe, 0xed, 0x7c, 0x33, 0x1a, 0xe8,
	0x24, 0x54, 0xd1, 0x1b, 0x7e, 0x8b, 0x22, 0x98, 0x0b, 0xae, 0xb8, 0xff, 0x11, 0x3a, 0x27, 0x11,
	0x17, 0xea, 0x2b, 0x8f, 0x42, 0xfc, 0x99, 0xa1, 0x54, 0xc4, 0x83, 0x9d, 0x98, 0x33, 0x85, 0x77,
	0xca, 0x73, 0xfa, 0xce, 0xa0, 0x15, 0x5a, 0x48, 0xf6, 0xa1, 0x96, 0x26, 0x5e, 0xcd, 0x90, 0xb5,
	0x34, 0xf1, 0x2f, 0xa0, 0xbb, 0x0a, 0x96, 0x73, 0xce, 0x24, 0x92, 0x2e, 0xb8, 0x28, 0x44, 0x11,
	0xa9, 0x9f, 0xd5, 0x28, 0x72, 0x08, 0x0d, 0xa9, 0xa8, 0xca, 0xa4, 0xe7, 0x1a, 0xae, 0x40, 0xfe,
	0x0b, 0xe8, 0xfc, 0xa0, 0x99, 0xc4, 0xd2, 0x57, 0xf2, 0x50, 0xa7, 0x5c, 0x70, 0xe5, 0xf2, 0xcf,
	0x05, 0xdf, 0x42, 0xed, 0xfc, 0x5a, 0xc7, 0x4f, 0x71, 0x61, 0xe3, 0xa7, 0xb8, 0x20, 0xff, 0x41,
	0xfd, 0x96, 0xce, 0x32, 0x2c, 0x52, 0xe4, 0xc0, 0xff, 0x00, 0x8d, 0xcf, 0xe9, 0x4c, 0xa1, 0xd0,
	0xf9, 0xe6, 0x02, 0x47, 0xe9, 0x5d, 0x11, 0x54, 0x20, 0xf2, 0x3f, 0xb8, 0x8a, 0x8e, 0xbd, 0x5a,
	0xdf, 0x1d, 0xb4, 0x8f, 0xdd, 0xe0, 0xfc, 0x3a, 0xd4, 0xd8, 0xbf, 0x77, 0xa0, 0x75, 0xc6, 0x19,
	0xc3, 0x58, 0x71, 0x41, 0x08, 0x6c, 0x5f, 0x2d, 0xe6, 0x58, 0x84, 0x9a, 0x37, 0x79, 0x0e, 0x70,
	0x9a, 0xc5, 0x53, 0x54, 0xdf, 0xe9, 0x8d, 0xad, 0x5a, 0x62, 0xc8, 0x4b, 0x00, 0x9d, 0xe0, 0x8c,
	0xb3, 0x51, 0x3a, 0xf6, 0xdc, 0x55, 0xfe, 0x12, 0x4d, 0xfa, 0xd0, 0x3e, 0xa5, 0xf1, 0x14, 0x59,
	0x62, 0xb2, 0x6c, 0x9b, 0x2c, 0x65, 0xca, 0xff, 0xed, 0xc0, 0x5e, 0x98, 0xb1, 0xc7, 0xf5, 0xd5,
	0xa3, 0x57, 0xc8, 0x28, 0x1b, 0x5a, 0xf9, 0x2c, 0xd4, 0x3d, 0x67, 0x12, 0xc5, 0x30, 0xb1, 0x1a,
	0xe6, 0x88, 0x1c, 0x01, 0x48, 0x9e, 0x89, 0x18, 0xf5, 0x4f, 0x4c, 0xd1, 0xf6, 0x31, 0x04, 0xcb,
	0x76, 0xc3, 0x92, 0x95, 0xbc, 0x86, 0x66, 0x82, 0x52, 0x19, 0xcf, 0xfa, 0x03, 0xcf, 0xa5, 0x8d,
	0x3c, 0x85, 0xed, 0x51, 0x3a, 0x53, 0x5e, 0xc3, 0xf8, 0xec, 0x04, 0xb9, 0xec, 0xa1, 0x21, 0x89,
	0x0f, 0xbb, 0x02, 0x6f, 0x68, 0xca, 0x2e, 0x4d, 0x62, 0x6f, 0xa7, 0xef, 0x0c, 0x9a, 0xe1, 0x1a,
	0xe7, 0xfb, 0xb0, 0x6f, 0xfb, 0x7c, 0x6c, 0x49, 0xfc, 0x7b, 0x17, 0x0e, 0x2f, 0xd2, 0x11, 0xc6,
	0x8b, 0x78, 0x86, 0x27, 0xb1, 0x4a, 0x39, 0xb3, 0xaa, 0x1c, 0x42, 0x83, 0x47, 0x93, 0xf3, 0xe5,
	0x52, 0x14, 0x48, 0x8f, 0x29, 0x7a, 0x30, 0xa6, 0x15, 0x43, 0x9e, 0x41, 0xeb, 0x16, 0x85, 0x4c,
	0x39, 0x5b, 0xca, 0xb4, 0x22, 0xf4, 0x7c, 0xa4, 0xe2, 0x82, 0x8e, 0xf1, 0x1b, 0x2a, 0x6a, 0xe7,
	0x53, 0xa2, 0x48, 0x0f, 0x9a, 0x3c, 0x9a, 0x60, 0xac, 0x86, 0x89, 0xd1, 0xa7, 0x15, 0x2e, 0xb1,
	0xfe, 0x13, 0x35, 0x9f, 0x34, 0xaa, 0xd4, 0xc3, 0x02, 0xe9, 0x3f, 0xe5, 0x0a, 0x5f, 0xa5, 0x28,
	0x8c, 0x18, 0xf5, 0xb0, 0xc4, 0x68, 0xbb, 0xa2, 0x62, 0x8c, 0xca, 0xd8, 0x9b, 0xb9, 0x7d, 0xc5,
	0x90, 0x57, 0xb0, 0x97, 0x7b, 0x17, 0x8b, 0xe2, 0xb5, 0x4c, 0xe1, 0x75, 0x52, 0x7b, 0xe5, 0x31,
	0xd6, 0x0b, 0x72, 0xaf, 0x35, 0x52, 0x6f, 0x0f, 0x8f, 0x26, 0x97, 0xe9, 0x2f, 0xf4, 0xda, 0x7d,
	0x67, 0xe0, 0x86, 0x16, 0xea, 0xce, 0xb2, 0xf9, 0x8c, 0xd3, 0x64, 0x98, 0x78, 0xbb, 0x79, 0x67,
	0x16, 0xfb, 0x47, 0x1b, 0xe6, 0x20, 0x37, 0x0f, 0xed, 0xf8, 0x8f, 0x03, 0xad, 0xe5, 0x05, 0x23,
	0x6f, 0xa0, 0x11, 0x66, 0x6c, 0xc2, 0x23, 0xb2, 0x1f, 0xac, 0xed, 0x75, 0xaf, 0x13, 0xac, 0xcf,
	0xdf, 0xdf, 0x22, 0x5f, 0xe0, 0xe0, 0x13, 0xaf, 0x14, 0x22, 0x4f, 0x82, 0xcd, 0x2b, 0xd0, 0xdb,
	0x60, 0x90, 0x45, 0xa2, 0x77, 0xd0, 0xb4, 0x47, 0x8f, 0x74, 0x83, 0xca, 0xf1, 0xec, 0x1d, 0x04,
	0xd5, 0x8b, 0x98, 0x87, 0xd8, 0xb3, 0x45, 0xba, 0x41, 0xe5, 0xc8, 0xf5, 0x0e, 0x82, 0xea, 0x4d,
	0xf3, 0xb7, 0xa2, 0x86, 0x39, 0xcf, 0xef, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x08, 0x0f, 0xe8,
	0x01, 0xb1, 0x05, 0x00, 0x00,
}
